name = "SFM"
uuid = "7046eeaf-8843-48ce-b028-0dfb19e02041"
authors = ["moussaddh <moussaddh@users.noreply.github.com>", "VEZY <VEZY@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshViz = "9ecf9c4f-6e5a-4b5e-83ae-06f2c7a661d8"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
PlyIO = "42171d58-473b-503a-8d5f-782019eb09ec"

[compat]
julia = "1.6"